# Configuration file for data ingestion process

# Root directory for storing artifacts
artifacts_root: artifacts

# Configuration for data ingestion
data_ingestion:
  # Directory for storing data related to data ingestion process
  root_dir: artifacts/data_ingestion
  # URL for downloading the source data
  source_URL: https://drive.google.com/file/d/1z0mreUtRmR-P-magILsDR3T7M6IkGXtY/view?usp=sharing
  # Path to the local data file after downloading
  local_data_file: artifacts/data_ingestion/data.zip
  # Directory for extracting the downloaded data
  unzip_dir: artifacts/
